/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as SpinRouteImport } from './routes/spin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MiningRouteImport } from './routes/mining'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinRoute = SpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningRoute = MiningRouteImport.update({
  id: '/mining',
  path: '/mining',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/mining': typeof MiningRoute
  '/signup': typeof SignupRoute
  '/spin': typeof SpinRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/mining': typeof MiningRoute
  '/signup': typeof SignupRoute
  '/spin': typeof SpinRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/deposit': typeof DepositRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/mining': typeof MiningRoute
  '/signup': typeof SignupRoute
  '/spin': typeof SpinRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/deposit'
    | '/history'
    | '/login'
    | '/mining'
    | '/signup'
    | '/spin'
    | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/deposit'
    | '/history'
    | '/login'
    | '/mining'
    | '/signup'
    | '/spin'
    | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/deposit'
    | '/history'
    | '/login'
    | '/mining'
    | '/signup'
    | '/spin'
    | '/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DepositRoute: typeof DepositRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MiningRoute: typeof MiningRoute
  SignupRoute: typeof SignupRoute
  SpinRoute: typeof SpinRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spin': {
      id: '/spin'
      path: '/spin'
      fullPath: '/spin'
      preLoaderRoute: typeof SpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining': {
      id: '/mining'
      path: '/mining'
      fullPath: '/mining'
      preLoaderRoute: typeof MiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DepositRoute: DepositRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MiningRoute: MiningRoute,
  SignupRoute: SignupRoute,
  SpinRoute: SpinRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
